---
# Install Nginx on Centos server
- hosts: 192.168.200.120
  become: true
  tasks: 

  - name: Install Nginx  on Centos server
    yum:
      name: nginx
      state: latest

#Install Apache2 on Ubuntu server
- hosts: 192.168.200.153
  tasks:

  - name: Install Apache2 on Ubuntu server
    apt:
      name: apache2
      state: latest
